[tool.black]
line-length = 80
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 80
extend-ignore = [
    "E203",  # Whitespace before ':', conflicts with Black
    "W503",  # Line break before binary operator, also conflicts with Black
]
